-- -------------------------------------------------------------
-- 
-- File Name: C:\Matlab\hdlsrc\pwm_generator\pwm_generator.vhd
-- Created: 2026-04-02 10:02:43
-- 
-- Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 1e-06
-- Target subsystem base rate: 1e-06
-- 
-- 
-- Clock Enable  Sample Time
-- -------------------------------------------------------------
-- ce_out        1e-06
-- -------------------------------------------------------------
-- 
-- 
-- Output Signal                 Clock Enable  Sample Time
-- -------------------------------------------------------------
-- Outport                       ce_out        1e-06
-- -------------------------------------------------------------
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: pwm_generator
-- Source Path: pwm_generator
-- Hierarchy Level: 0
-- Model version: 1.18
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;


ENTITY pwm_generator IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        --clk_enable                        :   IN    std_logic;
        --ce_out                            :   OUT   std_logic;
        Outport                           :   OUT   std_logic
        );
END pwm_generator;


ARCHITECTURE rtl OF pwm_generator IS

  -- Signals
  SIGNAL enb                              : std_logic;
  SIGNAL Constant_out1                    : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Add_out1                         : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Unit_Delay1_out1                 : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Duty_out1                        : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Less_Than_out1                   : std_logic;

BEGIN
  --enb <= '1'; --clk_enable;

  Constant_out1 <= to_unsigned(16#01#, 8);

  Unit_Delay1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Unit_Delay1_out1 <= to_unsigned(16#00#, 8);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Unit_Delay1_out1 <= Add_out1;
      END IF;
    END IF;
  END PROCESS Unit_Delay1_process;


  Add_out1 <= Unit_Delay1_out1 + Constant_out1;

  Duty_out1 <= to_unsigned(16#F0#, 8);
  -- original: Duty_out1 <= to_unsigned(16#80#, 8);

  
  Less_Than_out1 <= '1' WHEN Add_out1 < Duty_out1 ELSE
      '0';

 -- ce_out <= clk_enable;

  Outport <= Less_Than_out1;

END rtl;

